### ISSUE TITLE
Large tileset renders half of tile properties box invidible + random crash when selecting pixel scale.

### ISSUE THREAD

**Issue by Alucard648** [Sambo3975/SMBX2-Tileset-Creator#15]
- [x]  1. Screenshot says all:
![misalignment](https://user-images.githubusercontent.com/7596025/121785047-2d5a8b00-cbc0-11eb-9891-eb58bfee4823.png)

- [x]  2. got a random crash when selecting pixel scale.
[crash_latest.log](https://github.com/Sambo3975/SMBX2-Tileset-Creator/files/6642659/crash_latest.log)

Test tilesheet:
![unknown](https://user-images.githubusercontent.com/7596025/121785067-5418c180-cbc0-11eb-8add-358483ec1c7a.png)

**Comment by Sambo3975** [comment]
I can't reproduce either of these problems.

What's your screen resolution? It may be that the program doesn't properly support smaller resolutions and I didn't catch this because my monitors are 1440p.

~Have you opened this tileset image using a previous release? The pixel scale error could be a backward compatibility issue. Check and see if there's a file in your image's directory with the same name as the image but with a `.tileset.json` extension. If it's there, please provide a copy of it.~

Edit: Actually, that error you're getting on changing the pixel scale is a critical bug that will be encountered by anyone attempting to scale an image that has tiles placed on it. I will be releasing a hotfix for this later today. I still can't reproduce your first issue, though.

**Comment by Alucard648** [comment]
My screen resolution is 1280*1024

**Comment by Sambo3975** [comment]
It looks like that's the issue, then. The window's contents will be wider than 1280 pixels if the canvas is at its maximum width. I'll see what I can do.

**Comment by Sambo3975** [comment]
Added configurations for the maximum width and height of the displayed image. These can be accessed via File > Preferences. The default dimensions of the image display have also been lowered to 400x300 pixels.

Fixed the crash on changing the Pixel Scale option.

I will be ready to release the hotfix as soon as Wohl gets back to me on something I needed him to test.
